FIND_PATH(
  SMALL3D_INCLUDE_DIR
  NAMES
  small3d
  PATHS
  include)

FIND_LIBRARY(
  SMALL3D_LIBRARY
  NAMES
  small3d
  libsmall3d
  PATHS
  lib)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SMALL3D REQUIRED_VARS SMALL3D_LIBRARY SMALL3D_INCLUDE_DIR)
